server:
  port: 8081

github:
  client:
    id: 61fefd6a91c82539e61f
    secret: 9242dcbfcbd1ddb709a4f354f45f264afd908f08
    redirect_uri: http://localhost:8081/callback

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/blog?useSSL=false&useUnicode=true&characterEncoding=utf8&serverTimezone=UTC
    username: root
    password: welcomejack
    driver-class-name: com.mysql.cj.jdbc.Driver
  aop:
    auto: true
    proxy-target-class: true
  redis:
    host: 127.0.0.1
    port: 6379
    database: 0

mybatis:
  configuration:
    map-underscore-to-camel-case: true
  type-aliases-package: com.jackdyt.blog.mapper
  mapper-locations: classpath:mapper/*.xml



logging:
  file:
    path: blog.log
    max-history: 10
    max-size: 20MB
#  level:
#    com.jackdyt.blog.mapper: debug
