server:
  port: 8081

github:
  client:
    id: 61fefd6a91c82539e61f
    secret: 9242dcbfcbd1ddb709a4f354f45f264afd908f08
    redirect_uri: http://localhost:8081/callback

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/blog?useSSL=false&useUnicode=true&characterEncoding=utf8&serverTimezone=UTC
    username: root
    password: welcomejack
    driver-class-name: com.mysql.jdbc.Driver

mybatis:
  configuration:
    map-underscore-to-camel-case: true
  type-aliases-package: com.jackdyt.blog.mapper
  mapper-locations: classpath:mapper/*.xml

logging:
  file:
    path: blog.log
    max-history: 3
    max-size: 5MB
  level:
    com.jackdyt.blog.mapper: debug
