package com.jackdyt.blog.mapper;

import com.jackdyt.blog.model.Essay;
import com.jackdyt.blog.model.EssayExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.session.RowBounds;
import org.springframework.stereotype.Repository;

@Repository
public interface EssayMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table essay
     *
     * @mbg.generated Thu May 28 22:58:41 EDT 2020
     */
    long countByExample(EssayExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table essay
     *
     * @mbg.generated Thu May 28 22:58:41 EDT 2020
     */
    int deleteByExample(EssayExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table essay
     *
     * @mbg.generated Thu May 28 22:58:41 EDT 2020
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table essay
     *
     * @mbg.generated Thu May 28 22:58:41 EDT 2020
     */
    int insert(Essay record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table essay
     *
     * @mbg.generated Thu May 28 22:58:41 EDT 2020
     */
    int insertSelective(Essay record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table essay
     *
     * @mbg.generated Thu May 28 22:58:41 EDT 2020
     */
    List<Essay> selectByExampleWithBLOBsWithRowbounds(EssayExample example, RowBounds rowBounds);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table essay
     *
     * @mbg.generated Thu May 28 22:58:41 EDT 2020
     */
    List<Essay> selectByExampleWithBLOBs(EssayExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table essay
     *
     * @mbg.generated Thu May 28 22:58:41 EDT 2020
     */
    List<Essay> selectByExampleWithRowbounds(EssayExample example, RowBounds rowBounds);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table essay
     *
     * @mbg.generated Thu May 28 22:58:41 EDT 2020
     */
    List<Essay> selectByExample(EssayExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table essay
     *
     * @mbg.generated Thu May 28 22:58:41 EDT 2020
     */
    Essay selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table essay
     *
     * @mbg.generated Thu May 28 22:58:41 EDT 2020
     */
    int updateByExampleSelective(@Param("record") Essay record, @Param("example") EssayExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table essay
     *
     * @mbg.generated Thu May 28 22:58:41 EDT 2020
     */
    int updateByExampleWithBLOBs(@Param("record") Essay record, @Param("example") EssayExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table essay
     *
     * @mbg.generated Thu May 28 22:58:41 EDT 2020
     */
    int updateByExample(@Param("record") Essay record, @Param("example") EssayExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table essay
     *
     * @mbg.generated Thu May 28 22:58:41 EDT 2020
     */
    int updateByPrimaryKeySelective(Essay record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table essay
     *
     * @mbg.generated Thu May 28 22:58:41 EDT 2020
     */
    int updateByPrimaryKeyWithBLOBs(Essay record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table essay
     *
     * @mbg.generated Thu May 28 22:58:41 EDT 2020
     */
    int updateByPrimaryKey(Essay record);
}