package com.jackdyt.blog.model;

public class Admin {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column administrator.id
     *
     * @mbg.generated Fri Jun 19 21:54:02 EDT 2020
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column administrator.user_name
     *
     * @mbg.generated Fri Jun 19 21:54:02 EDT 2020
     */
    private String userName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column administrator.password
     *
     * @mbg.generated Fri Jun 19 21:54:02 EDT 2020
     */
    private String password;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column administrator.role
     *
     * @mbg.generated Fri Jun 19 21:54:02 EDT 2020
     */
    private String role;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column administrator.salt
     *
     * @mbg.generated Fri Jun 19 21:54:02 EDT 2020
     */
    private String salt;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column administrator.id
     *
     * @return the value of administrator.id
     *
     * @mbg.generated Fri Jun 19 21:54:02 EDT 2020
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column administrator.id
     *
     * @param id the value for administrator.id
     *
     * @mbg.generated Fri Jun 19 21:54:02 EDT 2020
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column administrator.user_name
     *
     * @return the value of administrator.user_name
     *
     * @mbg.generated Fri Jun 19 21:54:02 EDT 2020
     */
    public String getUserName() {
        return userName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column administrator.user_name
     *
     * @param userName the value for administrator.user_name
     *
     * @mbg.generated Fri Jun 19 21:54:02 EDT 2020
     */
    public void setUserName(String userName) {
        this.userName = userName == null ? null : userName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column administrator.password
     *
     * @return the value of administrator.password
     *
     * @mbg.generated Fri Jun 19 21:54:02 EDT 2020
     */
    public String getPassword() {
        return password;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column administrator.password
     *
     * @param password the value for administrator.password
     *
     * @mbg.generated Fri Jun 19 21:54:02 EDT 2020
     */
    public void setPassword(String password) {
        this.password = password == null ? null : password.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column administrator.role
     *
     * @return the value of administrator.role
     *
     * @mbg.generated Fri Jun 19 21:54:02 EDT 2020
     */
    public String getRole() {
        return role;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column administrator.role
     *
     * @param role the value for administrator.role
     *
     * @mbg.generated Fri Jun 19 21:54:02 EDT 2020
     */
    public void setRole(String role) {
        this.role = role == null ? null : role.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column administrator.salt
     *
     * @return the value of administrator.salt
     *
     * @mbg.generated Fri Jun 19 21:54:02 EDT 2020
     */
    public String getSalt() {
        return salt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column administrator.salt
     *
     * @param salt the value for administrator.salt
     *
     * @mbg.generated Fri Jun 19 21:54:02 EDT 2020
     */
    public void setSalt(String salt) {
        this.salt = salt == null ? null : salt.trim();
    }
}